<?php

namespace Database\Seeders;

use App\Models\Coupon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CouponSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Coupon::insert([
            [
                'image' => '1712761557.jpg',
                'name' => 'to the dw',
                'price' => 2280.30,
                'category_id' => 8,
                'download_limit' => 10,
                'retailer_id' => 2,
                'retail_price' => 3455.00,
                'discount_now_price' => 34.00,
                'discount_percentage' => 'Discount Percent',
                'start_date' => '2024-07-12 15:05:57',
                'end_date' => '2024-05-30 15:05:57',
                'qr_code' => 'c8P7zHd7aIbSkP',
                'discount_description' => 'wefweew',
                'discount_code' => 'oMoz656j',
                'offer_type' => 'Exclusive Offers',
                'approval_status' => 'NEW',
                'created_by' => 2,
                'modified_by' => 2,
            ],
            [
                'image' => '1701777161.jpg',
                'name' => 'Discount iPhone 14 Pro',
                'price' => 679.15,
                'category_id' => 7,
                'download_limit' => 10,
                'retailer_id' => 2,
                'retail_price' => 799.00,
                'discount_now_price' => 15.00,
                'discount_percentage' => 'Discount Percent',
                'start_date' => '2023-12-06 20:25:46',
                'end_date' => '2024-05-31 20:25:46',
                'qr_code' => '7fppUlFodFQlor',
                'discount_description' => 'The iPhone 15 and 15 Plus start at $799 and offer a good balance between functionality, longevity, and price, but if cost is the major factor for you.',
                'discount_code' => '7rQP2qkH',
                'offer_type' => 'Weekly Offers',
                'approval_status' => 'Approved',
                'created_by' => 2,
                'modified_by' => 2,
            ],
            [
                'image' => '1701777976.jpg',
                'name' => '2023 MacBook Pro Exclusive Offer',
                'price' => 1949.35,
                'category_id' => 7,
                'download_limit' => 10,
                'retailer_id' => 2,
                'retail_price' => 2999.00,
                'discount_now_price' => 35.00,
                'discount_percentage' => 'Discount Percent',
                'start_date' => '2023-12-05 20:25:22',
                'end_date' => '2024-08-02 20:25:22',
                'qr_code' => 'GSvIWC5UxLS3FT',
                'discount_description' => 'If you’re a creative professional or a hardcore power user, or you simply feel like splurging on the best that Apple has to offer, especially with this discount',
                'discount_code' => 'Z7hNLUmw',
                'offer_type' => 'Exclusive Offers',
                'approval_status' => 'Approved',
                'created_by' => 2,
                'modified_by' => 2,
            ],
            [
                'image' => '1701778430.jpg',
                'name' => 'Sony WH-1000XM5 Wireless Headphones',
                'price' => 0.00,
                'category_id' => 11,
                'download_limit' => 10,
                'retailer_id' => 2,
                'retail_price' => 98.76,
                'discount_now_price' => 0.00,
                'discount_percentage' => 'Buy one get free ear pods',
                'start_date' => '2023-12-05 20:24:11',
                'end_date' => '2024-06-27 20:24:11',
                'qr_code' => '8g0RmXzXUEk6Y1',
                'discount_description' => 'The Sony WH-1000XM5 is the successor to the WH-1000XM4, and has a refreshed design and improved sound quality and ANC.',
                'discount_code' => 'BlxpEbFo',
                'offer_type' => 'Weekly Offers',
                'approval_status' => 'Approved',
                'created_by' => 2,
                'modified_by' => 2,
            ],
            [
                'image' => '1701778612.png',
                'name' => 'PS5 gaming Console',
                'price' => 540.00,
                'category_id' => 24,
                'download_limit' => 10,
                'retailer_id' => 2,
                'retail_price' => 900.00,
                'discount_now_price' => 40.00,
                'discount_percentage' => 'Discount Percent',
                'start_date' => '2023-12-05 20:24:36',
                'end_date' => '2024-07-20 20:24:36',
                'qr_code' => 'YoneuXarl91ed5',
                'discount_description' => 'PS5 consoles have seen a first-time discount. Come take advantage of this offer while stock lasts',
                'discount_code' => '6rPKPWzU',
                'offer_type' => 'Exclusive Offers',
                'approval_status' => 'Approved',
                'created_by' => 2,
                'modified_by' => 2,
            ],
            [
                'image' => '1702371675.jpg',
                'name' => 'test coupon',
                'price' => 43.12,
                'category_id' => 8,
                'download_limit' => 10,
                'retailer_id' => 2,
                'retail_price' => 56.00,
                'discount_now_price' => 23.00,
                'discount_percentage' => 'Discount Percent',
                'start_date' => '2023-12-12 20:25:01',
                'end_date' => '2024-07-06 20:25:01',
                'qr_code' => 'hVruQ5qvdwKADu',
                'discount_description' => 'test',
                'discount_code' => 'FmhMeHwq',
                'offer_type' => 'Weekly Offers',
                'approval_status' => 'Approved',
                'created_by' => 2,
                'modified_by' => 2,
            ],
        ]);
    }
}
